name: Publish Docker image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'build.gradle.kts'
      - '.github/workflows/docker.yml'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: DockerDeploy
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean release
          gradle-version: wrapper
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: minnced
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        working-directory: containers
        run: docker compose build
      - name: Push to Docker Hub
        working-directory: containers
        run: docker compose push
